import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { kanit, taviraj, staatliches } from "@/utils/font";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${kanit} ${taviraj} ${staatliches}`}>
        <Navbar />
        <div className="flex flex-col min-h-screen">
          <main className="flex-grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
